# Generated by Django 2.1.3 on 2018-12-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kintai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.IntegerField(max_length=6, verbose_name='社員No.')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('start', models.TimeField(verbose_name='就業開始時刻')),
                ('end', models.TimeField(verbose_name='就業終了時刻')),
            ],
        ),
    ]
